dart-lang/dart-syntax-highlight

grammars/dart.json

This mirrors [a fix](https://github.com/Dart-Code/Dart-Code/commit/03a19d7f40c35beaac64eaae86ce3eafed1c5dee) from Dart-Code for https://github.com/Dart-Code/Dart-Code/issues/2575.
Before, unicode characters were treated as valid in interpolated variable names:
This made is seem like braces were required, but they are not:

Don't match unicode characters in interpolated variable names

---

grammars/dart.json

This adds colour to the `if`s in conditional imports (previously they were white):
I've marked them as "control keywords" to match the color of other `if`s in the program, although I'm not sure if that logic is entirely sound. Having them a different color to other `if`s looked a little odd (in this theme, control keywords are pink and other keywords blue).
(I've done the same [in LSP semantic tokens version](https://dart-review.googlesource.com/c/sdk/+/203560/) - we should keep them in-sync if we decide to change it here).
@devoncarew

Color "if"s in conditional imports/exports

---

grammars/dart.json

In the existing grammar, interpolation expressions are detected by `${` and then end with `}`. This falls down if there are `}` inside the expression that are not the end of the interpolated part of the string.
This change instead reuses the other parts of the grammar to parse this code, so the correct `}` should be used (I don't know that it's 100% reliable, but it seems a significant improvement).
Left: before, right: after.
Most of the code is orange because the `} `in the string on line 14 was being considered the end of the expression, and then the subsequent quote assumed to start a new string.
I had originally planned to just simplify the grammar by removing the colouring for interpolated expressions (to allow something like LSP Semantic Tokens to lay this on top for clients that …

Reuse grammar inside interpolation expressions instead of just looking for `}`

---

grammars/dart.json

This syncs with the latest Dart-Code syntax highlight file. It includes three fixes (two of which previously shipped in Dart-Code, and the last one is new today):
- Color `if`s in conditional imports
- Handle interpolated expressions better (by nesting rules to more reliably detect the end of the expression instead of assuming the first `}`)
https://github.com/Dart-Code/Dart-Code/issues/2056
- Handle nested expressions better (don't eat any line that starts with `*    ` assuming it won't end a comment)
https://github.com/Dart-Code/Dart-Code/issues/3546
I've compared the results across some test files and several large SDK files and the only differences I spotted are those the fixes are intended to address (screenshots in the linked issues above).

Fix nested comment highlighting, colour if's in conditional imports, improve interpolated expressions

---

grammars/dart.json

The recent changes I made to handle type args better did not take into account `extends` inside the args, which resulted in the type args not being parsed at all, which caused the function expressions to fail to match:
Similar was true for `?` in nullable types inside type args. This change should handle both:
Most VS Code users wouldn't see this because semantic tokens would quickly be overlaid and fix it, but I'm trying to minimise the number of color changes when the semantic tokens become available.

Allow "extends" and "?" in type args

---

grammars/dart.json

This came up in https://github.com/Dart-Code/Dart-Code/issues/3888. Function invocations that have `?` or `!` were not being classified as functions. This change allows either of those to appear just before the `(` and still be treated as a function identifier.
(@devoncarew I'm not sure if someone suitable gets notifications of PRs here, if they are and shouldn't ping you, lmk!)

Allow ? and ! in function before ( in function identifiers

---

grammars/dart.json

This rule was more complicated than it needed to be to support classes/void/built-in types and was accidentally nesting capture groups (which complicates applying the grammar to source using a simple stack), so this change just splits it up.
Visually, everything looks identical in VS Code, and testing using some tests in https://github.com/dart-lang/dart-syntax-highlight/pull/28 and an npm tool (since the Dart parser doesn't handle the current grammar yet), the output is the same except for no longer wrapping the class span around the entire type args (something I don't think was intended).
(I am working on completing https://github.com/dart-lang/dart-syntax-highlight/pull/28, but I need to get the Dart parser to be able to parse the current version of the grammar file, which it currently …

Split class-identifier rule up

---

.github/workflows/dart.yml
CONTRIBUTING.md
analysis_options.yaml
pubspec.yaml
test/golden_test.dart
test/goldens/classes.dart.golden
test/goldens/comments.dart.golden
test/goldens/control.dart.golden
test/goldens/directives.dart.golden
test/goldens/functions.dart.golden
test/goldens/literals.dart.golden
test/goldens/misc.dart.golden
test/goldens/operators.dart.golden
test/goldens/parameters.dart.golden
test/goldens/string_interpolation.dart.golden
test/support/span_parser.dart
test/test_files/classes.dart
test/test_files/comments.dart
test/test_files/control.dart
test/test_files/directives.dart
test/test_files/functions.dart
test/test_files/literals.dart
test/test_files/misc.dart
test/test_files/operators.dart
test/test_files/parameters.dart
test/test_files/string_interpolation.dart

@bkonyi @devoncarew it's been bugging me that we had no good way to syntax changes besides reviewing the results manually. Dart-Code has [an open PR](https://github.com/Dart-Code/Dart-Code/pull/4067) (that will need to be redirect here when ready) that refactors quite a lot of this code that re-reminded me about this.
I found https://github.com/PanAeon/vscode-tmgrammar-test and added some basic tests to the Dart-Code repo, but really there should be tests here too. @bkonyi pointed out DevTools has some grammar parsing so rather than setting up TypeScript/npm here, it seems like we might be able to replicate that without much effort.
This PR is not complete (it has span_parser lifted from DevTools with some slight tweaks, and I think it's failing to parse some of my test code) but I wanted …

Add some basic testing using some test files and a golden text representation of tokens

---

analysis_options.yaml
test/goldens/records.dart.golden
test/test_files/records.dart

@devoncarew the existing grammar parses this syntax as expected without any changes, this is just adding some goldens to ensure that continues to be the case.
While adding this, I noticed the copyright headers say "Copyright 2022 The Chromium Authors" (and not "Dart authors") because I took the original sample files from flutter/devtools (which has that in all of its headers). Should these be changed?

Add test cases for records

---

CHANGELOG.md
grammars/dart.json
test/goldens/classes.dart.golden
test/goldens/functions.dart.golden
test/goldens/misc.dart.golden
test/goldens/parameters.dart.golden
test/test_files/classes.dart
test/test_files/misc.dart

Fixes https://github.com/Dart-Code/Dart-Code/issues/4216.
@devoncarew this improves how type args are parsed slightly which fixes some issues where the type args would eat much more than it should, preventing some colouring from appearing.
Before:
After:
Additionally, it handles get/set as function names better (more closely matching semantic tokens).
Before:
After:
I added some additional tests in the first commit (with corresponding golden updates for the current behaviour) and then the grammar change + golden changes they result in in the subsequent commit.

Fix handling of type params/args w/ extends, and get/set as function names

---

CHANGELOG.md
grammars/dart.json
test/goldens/comments.dart.golden
test/test_files/comments.dart

First commit adds a golden showing the current behaviour, and the second commit includes the fix and the diff it makes to the tests.
Fixes https://github.com/dart-lang/dart-syntax-highlight/issues/45.

Fix highlighting of comments inside type args/parameters

---

CHANGELOG.md
grammars/dart.json
test/goldens/inline.dart.golden
test/test_files/inline.dart

See https://github.com/dart-lang/sdk/issues/49734 and https://github.com/dart-lang/language/blob/master/accepted/future-releases/inline-classes/feature-specification.md.
Inline is only detected as part of class, since the spec says:
> The token `inline` is not made a built-in identifier: the reserved word `class` that occurs right after `inline` serves to disambiguate the inline class declaration with a fixed lookahead.

Add support for inline classes

---

CHANGELOG.md
grammars/dart.json
test/goldens/literals.dart.golden
test/goldens/string_interpolation.dart.golden

I'm migrating to use TextMate grammars on dart.dev and docs.flutter.dev, but found that while I can highlight the punctuation of expression interpolation with `string.interpolated.expression`, the same didn't work for identifier interpolation.
\cc @DanTup

Include opening `$` in identifier interpolation scope

---

CHANGELOG.md
grammars/dart.json
test/goldens/comments.dart.golden
test/test_files/comments.dart

Also removes what appears to be a duplicate pattern entry for this match. Let me know if it exists for a reason.

Don't mark empty backticks as inline code

---

CHANGELOG.md
grammars/dart.json
test/goldens/classes.dart.golden
test/test_files/classes.dart

This fixes highlighting of methods named get/set that have type parameters. We would previously match `get`/`set` as keywords unless followed by a `(`, but now we check for both `(` and `<`.
See https://github.com/Dart-Code/Dart-Code/issues/4957

Fix highlighting of generic methods named get/set

---

grammars/dart.json
test/goldens/control.dart.golden
test/goldens/functions.dart.golden
test/goldens/patterns.dart.golden
test/goldens/records.dart.golden

This defines the scope `keyword.control.return.dart` which is useful to color the return key separately. This allows to replicate the feature found in the Eclipse Java editor:
Some other languages already provide separate scopes for the `return` keyword:
- csharp defines `keyword.control.flow.return.cs`
- scss defines `keyword.control.return.scss`
- php even defines separate scopes for all keywords using: `keyword.control.${1:/downcase}.php`
```json
{
"match": "(?x)\n\\b(\n  break|case|continue|declare|default|die|do|\n  else(if)?|end(declare|for(each)?|if|switch|while)|exit|\n  for(each)?|if|return|switch|use|while|yield\n)\\b",
"captures": {
"1": {
"name": "keyword.control.${1:/downcase}.php"
}
}
},
```
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor …

define keyword.control.return.dart

---

CHANGELOG.md
grammars/dart.json

This was overlooked from https://github.com/dart-lang/dart-syntax-highlight/pull/58
@jwren

Bump version + update changelog

---

.vscode/settings.json
CHANGELOG.md
grammars/dart.json
test/goldens/literals.dart.golden
test/goldens/string_interpolation.dart.golden
test/test_files/string_interpolation.dart

Previously we would treat the first `}` in an interpolation expression as the end of the expression. So in:
```dart
var a = " ${ {} }";
```
The interpolation scope would end too soon. Additionally, VS Code's bracket matching used for colouring uses these scopes to know what's a string and what is new code inside a string, so without using `meta.embedded` the colours would be incorrect. Ideally I would have liked to handle that without changing the scope, but I've so far been unable to make it work with custom scopes. I've filed https://github.com/microsoft/vscode/issues/210053 but since other languages are using scope names like `meta.embedded` I think we should go ahead with it too (and we were already mapping to `meta.embedded` for semantic tokens).
Before/after with this change below: …

Fix handling of closing braces + use meta.embedded.* for interpolated expressions in string

---

CHANGELOG.md
grammars/dart.json
test/goldens/augmentation.dart.golden
test/goldens/augmented.dart.golden
test/goldens/classes.dart.golden
test/test_files/augmentation.dart
test/test_files/augmented.dart
test/test_files/classes.dart

This adds colouring for the new terms used in macros and augmentations.
The modifiers in the imports/library declarations are coloured the same way as `import`, `library` etc. and `augmented` is treated like `super` (I'm not completely sold on that, but otherwise it would just be uncoloured like other identifiers and I feel like it should stand out as being special).
(as usual, the colours may change a little if/when semantic tokens are available)
@jwren

Add colouring for macros and augmentations

---

CHANGELOG.md
grammars/dart.json
pubspec.yaml
test/goldens/comments.dart.golden
test/test_files/comments.dart

While investigating https://github.com/dart-lang/dart-syntax-highlight/issues/11 I found a difference in how VS Code and GitHub/linguist handle `when` in the grammars.
In VS Code, when a `when` pattern stops matching, any open scopes from nested rules are ended, whereas on GitHub they are not. This means an unterminated triple-backtick block on GitHub can escape out of the surrounding comment.
The discussion in https://github.com/github-linguist/linguist/issues/7015 concluded that VS Code's behaviour is incorrect, and GitHub's behaviour (to just keep processing the nested rules until they end before re-evaluating the `while`) matches TextMate.
Since this isn't well specified and it's not clear if VS Code will change behaviour to match, this change stops using `while` in the grammar and …

Switch from using "while" to "end" and adjust nested rules accordingly

---

CHANGELOG.md
grammars/dart.json
test/goldens/comments.dart.golden
test/test_files/comments.dart

This fixes the issue that was noted at https://github.com/dart-lang/dart-syntax-highlight/pull/75#issuecomment-2449709951 which was caused by an indented `*/` being considered part of a code block and not triggering the end of the comment.

Fix issue with indented closing block comment marker
